import {inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter=Inter({subsets:["latin"]});
function Header(){
  return (
    <header>
      <div>
        <nav>
          <div>
            <Link href="/"> Abcdef</Link>
          </div>
          <div>
            <Link href="/mountain"> Mountain Info</Link>
          </div>
        </nav>
        
      </div>
    </header>
  );
}
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className} > {children}
      </body>
    </html>
  );
}
